# Generated by Django 3.1.7 on 2021-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Craw',
            fields=[
                ('snum', models.AutoField(db_column='sNum', primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('lname', models.CharField(db_column='lName', max_length=50)),
                ('title', models.TextField()),
                ('degree', models.CharField(max_length=50)),
                ('acheck', models.CharField(db_column='aCheck', max_length=50)),
                ('con', models.TextField()),
                ('sdate', models.DateTimeField(db_column='sDate')),
                ('edate', models.DateTimeField(db_column='eDate')),
            ],
            options={
                'db_table': 'craw',
                'managed': False,
            },
        ),
    ]
